-- =============================================  
-- Author:  Dhirendra K Singh  
-- Create date: 19-April-2022  
-- Description: OnWeb_ReAdmission
-- =============================================  
ALTER procedure [dbo].[PR_OnWeb_ReAdmission]
 @FromDate Varchar(50),
 @ToDate Varchar(50)   
as  
-- PR_OnWeb_ReAdmission '01-Jan-2022','10-Jan-2022'  
begin  
SET NOCOUNT ON; 
SELECT RE.IDF_READMISSION,P.PATIENT_SSN, PD.PATIENT_NAME,DA.FULLDATE AS DISCHARGE_DATE,D.FULLDATE AS ADMISSION_DATE 
,h.address3,C.DEPARTMENT_NAME AS READMISSION_DEPARTMENT, CE.DEPARTMENT_NAME AS DISCHARGE_DEPARTMENT, ACP.CARE_PROVIDER_NAME AS ADMISSION_CARE_PROVIDER, DCP.CARE_PROVIDER_NAME AS DISCHARGE_CARE_PROVIDER,
AG.FULLDATE as DATEOFBIRTH,SE.SEX,RE.PATIENT_ID,FAD.FULLDATE,
(SELECT COUNT(FP.IDF_PROBLEM)FROM F_PROBLEM FP WHERE FP.PATIENT_ID=RE.PATIENT_ID AND FP.ENTERED_ON_DATE_ID=RE.ADMISSION_DATE_ID AND FP.PROBLEM_STATUS_ID=2 AND FP.PROBLEM_CONDITION_ID<>2) AS READMISSION_PROBLEM_COUNT,
(SELECT COUNT(FP.IDF_PROBLEM)FROM F_PROBLEM FP WHERE FP.PATIENT_ID=RE.PATIENT_ID AND FP.ENTERED_ON_DATE_ID>=RE.F_ADMISSION_DATE_ID AND FP.ENTERED_ON_DATE_ID<=RE.DISCHARGE_DATE_ID AND FP.PROBLEM_STATUS_ID=2 AND FP.PROBLEM_CONDITION_ID<>2) AS DISCHARGE_PROBLEM_COUNT
FROM f_readmission RE 
LEFT JOIN f_patient P ON (RE.PATIENT_ID=P.IDF_PATIENT) 
LEFT JOIN d_patient_details PD ON (PD.IDD_PATIENT_DETAILS=RE.PATIENT_DETAIL_ID) 
LEFT JOIN d_date D ON (D.IDD_DATE=RE.ADMISSION_DATE_ID) 
LEFT JOIN d_date DA ON (DA.IDD_DATE=RE.DISCHARGE_DATE_ID)
LEFT JOIN D_HIS_HOSPITAL_LOCATION H ON (H.IDD_HIS_HOSPITAL_LOCATION=RE.HIS_HOSPITAL_LOCATION_ID)
LEFT JOIN D_CARE_PROVIDERS ACP ON (ACP.IDD_CARE_PROVIDERS=RE.ADMISSION_CARE_PROVIDER_ID)
LEFT JOIN D_CARE_PROVIDERS DCP ON (DCP.IDD_CARE_PROVIDERS=RE.DISCHARGE_CARE_PROVIDER_ID)
LEFT JOIN D_DATE AG ON (AG.IDD_DATE=P.DATE_OF_BIRTH_ID)
LEFT JOIN D_SEX SE ON (SE.IDD_SEX=P.SEX_ID)
LEFT JOIN D_DEPARTMENT C ON (C.IDD_DEPARTMENT=RE.ADMISSION_DEPARTMENT_ID) 
LEFT JOIN D_DEPARTMENT CE ON (CE.IDD_DEPARTMENT=RE.DISCHARGE_DEPARTMENT_ID) 
LEFT JOIN D_DATE FAD ON (FAD.IDD_DATE=RE.F_ADMISSION_DATE_ID)
WHERE d.fulldate >=Convert(DateTime,@FromDate)
and d.fulldate <=Convert(DateTime,@ToDate)
ORDER BY 
DA.FULLDATE   ASC             

End